INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'CustomerType', 'ENTERPRICE', '企业','ACTIVE');--商户类型
INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'IndustryType', 'Education', '教育','ACTIVE');--所属行业
INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'AppType', 'NORMAL', '标准版','ACTIVE');--应用类型,标准版还是行业版
INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'AppType', 'INDUSTRY', '行业版','ACTIVE');
INSERT INTO YMF_BUSINESS
(ID, OPTIMISITC, BIZ_CODE, CREATE_TIME, UPDATE_TIME, STATUS, BIZ_NAME)
VALUES(SEQ_BUSINESS_ID.nextval, 0, 'ZGT', '2016-07-01-00.00.00.000000', null, 'ACTIVE', '掌柜通');
INSERT INTO YMF_BUSINESS
(ID, OPTIMISITC, BIZ_CODE, CREATE_TIME, UPDATE_TIME, STATUS, BIZ_NAME)
VALUES(SEQ_BUSINESS_ID.nextval, 0, 'YMF', '2016-07-01-00.00.00.000000', null, 'ACTIVE', '易码付');
INSERT INTO YMF_QRCODE
(ID, OPTIMISITC, CUSTOMER_NUMBER, CREATE_TIME, UPDATE_TIME, QR_ID, FTP_URL, STATUS)
VALUES(SEQ_QRCODE_ID.nextval, 0, '10040003669', '2016-08-12-20.19.20.153000', null, 'QR123456', 'http://localhost:8080', 'ACTIVE');

--- 数据字典初始化 ---
insert into YMF_DICTIONARY VALUES (NEXT VALUE FOR SEQ_DICTIONARY_ID, 0, 'OperateType', 'ADD', '增加', 'ACTIVE');
insert into YMF_DICTIONARY VALUES (NEXT VALUE FOR SEQ_DICTIONARY_ID, 0, 'OperateType', 'DELETE', '删除', 'ACTIVE');
insert into YMF_DICTIONARY VALUES (NEXT VALUE FOR SEQ_DICTIONARY_ID, 0, 'OperateType', 'UPDATE', '修改', 'ACTIVE');
insert into YMF_DICTIONARY VALUES (NEXT VALUE FOR SEQ_DICTIONARY_ID, 0, 'OperateType', 'SELECT', '查询', 'ACTIVE');

 INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'PayType', 'WECHAT_C_PAYMENT', 'wap微信H5支付','ACTIVE');--支付方式
 INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'PayType', 'WECHAT_A_PAYMENT', '微信公众号支付','ACTIVE');--支付方式
 INSERT INTO YMF_DICTIONARY
(ID, OPTIMISITC, "TYPE", CODE, NAME,Status)
VALUES(SEQ_DICTIONARY_ID.nextval, 0, 'PayType', 'NC_PAYMENT', '银行卡WAP支付','ACTIVE');--支付方式