ALTER TABLE YMF.TBL_FUNCTION
  ADD COLUMN FUNC_LEVEL VARCHAR(20);
ALTER TABLE YMF.TBL_FUNCTION
  ADD COLUMN AVALIAVLE SMALLINT;
ALTER TABLE YMF.TBL_FUNCTION
  ADD COLUMN REASON VARCHAR(128);
ALTER TABLE YMF.TBL_ROLE_FUNC
  RENAME COLUMN ROLE TO ROLE_ID;
ALTER TABLE YMF.TBL_ROLE_FUNC
  ALTER ROLE_ID SET DATA TYPE VARCHAR(50);

CREATE TABLE YMF.TBL_ROLE (
  ID          VARCHAR(50) PRIMARY KEY                                          NOT NULL,
  PARENT_ID   VARCHAR(50),
  ROLE_NAME   VARCHAR(50)                                                      NOT NULL,
  ROLE_CODE   VARCHAR(20),
  OPERATOR    VARCHAR(50)                                                      NOT NULL,
  DESCRIPTION VARCHAR(256),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP                              NOT NULL,
  UPDATE_TIME TIMESTAMP
);
COMMENT ON TABLE YMF.TBL_ROLE IS '来客用户角色表';
CREATE UNIQUE INDEX YMF.TBL_ROLE_ROLE_CODE_IDX
  ON YMF.TBL_ROLE (ROLE_CODE);
CREATE SEQUENCE YMF.SEQ_YMF_ROLE_ID AS BIGINT INCREMENT BY 1 START WITH 1 NO MAXVALUE;
GRANT INSERT, UPDATE, DELETE, SELECT ON TABLE YMF.TBL_ROLE TO USER LIKER;
GRANT SELECT ON TABLE YMF.TBL_ROLE TO USER QUERY;


INSERT INTO YMF.TBL_ROLE (ID, PARENT_ID, ROLE_NAME, ROLE_CODE, OPERATOR, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES ('ARO00000000000001', '', '来客超级用户', 'LIKER_ADMIN',
        'jiawen.huang', '来客超级用户，没有上级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP INDEX YMF.ROLE_FUNC_ROLE_IDX;
CREATE UNIQUE INDEX YMF.ROLE_FUNC_UNIQUE_IDX
  ON YMF.TBL_ROLE_FUNC (FUNCTION_ID, ROLE_ID);
