ALTER TABLE YMF.TBL_OPERATE_RECODE ALTER COLUMN BIZ_PARAM SET DATA TYPE VARCHAR(256);
ALTER TABLE YMF.TBL_USER
  ADD COLUMN INVITE_CODE VARCHAR(20);
ALTER TABLE YMF.TBL_USER
  ADD COLUMN ALLIANCE_INVITE_CODE VARCHAR(20);
ALTER TABLE YMF.TBL_ACCOUNT_OPEN
  ADD COLUMN ACCOUNT_TYPE VARCHAR(20);
ALTER TABLE YMF.TBL_ACCOUNT_OPEN
  ADD COLUMN LOL_OPEN_STATUS VARCHAR(20);
ALTER TABLE YMF.TBL_ACCOUNT_OPEN
  ADD COLUMN OCR_LEGAL_ID_CARD VARCHAR(100);
ALTER TABLE YMF.TBL_ACCOUNT_OPEN
  ADD COLUMN OCR_SETTLE_CARD_NO VARCHAR(100);
UPDATE YMF.TBL_ACCOUNT_OPEN
SET ACCOUNT_TYPE = 'LK'
WHERE ACCOUNT_TYPE IS NULL OR ACCOUNT_TYPE = '';
ALTER TABLE YMF.TBL_USER
  ADD COLUMN APP_SOURCE VARCHAR(20);
UPDATE YMF.TBL_USER
SET APP_SOURCE = 'LIKER'
WHERE APP_SOURCE IS NULL OR APP_SOURCE = '';
DROP INDEX YMF.USER_PHONE_NO_IDX;
CREATE INDEX YMF.USER_PHONE_NO_IDX
  ON YMF.TBL_USER (PHONE_NO);
CREATE UNIQUE INDEX YMF.USER_PHONE_AND_SOURCE_IDX ON YMF.TBL_USER (PHONE_NO, APP_SOURCE);
ALTER TABLE YMF.TBL_ACCOUNT_OPEN ALTER COLUMN OPEN_STATUS DROP NOT NULL;
